apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: anvil
resources:
  - namespace.yaml
  - service-account.yaml
  - rbac.yaml
  - runtime-config.yaml
  - deployments.yaml
  - services.yaml
  - certificate.yaml
  - ingress.yaml
